### ISSUE TITLE
Do Vision API  support Indian Language like Malayalam?

### ISSUE THREAD

**Issue by flipmedia** [GoogleCloudPlatform/cloud-vision#100]
Hi Sir,
Sorry to post this on issues part. My Concern is , do google Vision API Support South Indian language like Malayalam. In web URL: https://cloud.google.com/vision/, I tried English image it works , but Malayalam image is not . If it allow , we plan a mobile app using Vision API for blind community for OCR Purpose in Malayalam. Waiting Your fast reply soon
N.B I attach a sample malayalam image to check you for OCR...

Anes
![test](https://cloud.githubusercontent.com/assets/610256/20088750/3816b9d0-a5a8-11e6-8281-7c6ffd2f80cf.jpg)

**Comment by tswast** [comment]
Supported languages are listed here: https://cloud.google.com/vision/docs/languages

Note: issues on this repository are for samples, not the product itself. As such, I'm closing this issue.

I recommend requesting this language support on https://groups.google.com/forum/#!forum/cloud-vision-discuss which is monitored by the engineering team.

**Comment by rohittp0** [comment]
Malayalam is not currently supported by Vision API. You could try Tesseract.
