### ISSUE TITLE
Cleaning Up Cloud Vision OCR Text Detection responses? 

### ISSUE THREAD

**Issue by gesabo** [GoogleCloudPlatform/cloud-vision#105]
Is there a feature that I can pass into my request that will parse the OCR text I'm getting back into, for example, english words and names?  I'm having difficulty doing such on the client side while maintaining performance.

**Comment by tswast** [comment]
It's not built into the Cloud Vision API, but you could pass the text from the response to the Cloud Natural Language API - https://cloud.google.com/natural-language/

The annotateText method supports parsing English syntax (and other languages) as well as entity (proper names) detection. https://cloud.google.com/natural-language/reference/rest/v1/documents/annotateText

**Comment by gesabo** [comment]
@tswast will do, thanks for getting back to me so quickly!
