### ISSUE TITLE
Client Not Synched Up to Server Update _KEY_MAP values Missing

### ISSUE THREAD

**Issue by yatuzhang** [GoogleCloudPlatform/cloud-vision#111]
Hi,

There seems to be some changes in JSON response returned from the server, but the client library is not up-to-date.

For instance, I see that there is now a key called fullTextAnnotation returned by the server, but the corresponding _KEY_MAP is missing this key in the client library, causing KeyError.

Would there be a possibility of cross checking the versions in the future?

**Comment by jerjou** [comment]
Hello!
Which sample are you looking at?

(We're actually working on moving the samples in this repo to a more centralized repo for our samples; so there might be a more updated sample, as well)

**Comment by yatuzhang** [comment]
Sorry, I should have opened this issue under https://github.com/GoogleCloudPlatform/google-cloud-python instead...  as it is the issue with the client library.

I am referring errors from the client library for annotations.py[https://github.com/GoogleCloudPlatform/google-cloud-python/blob/8f3881adb20e0783599add7a3528e7aa69e1093e/vision/google/cloud/vision/annotations.py] when using text detection API.
