### ISSUE TITLE
ImageSource supports "gcs" at moment, NO "imageUri" .

### ISSUE THREAD

**Issue by XinyueZ** [GoogleCloudPlatform/cloud-vision#114]
I saw the official RESTApi document, there should be an  ```imageUri```  that supports normal public address.  But I can not find it in Android SDK.

Will it be planned to add ?

**Comment by tswast** [comment]
The Android SDK for vision is related but separate from this project. You can look at how to use the REST API directly using this sample.

https://github.com/GoogleCloudPlatform/cloud-vision/blob/master/android/CloudVision/app/src/main/java/com/google/sample/cloudvision/MainActivity.java
