### ISSUE TITLE
Following the text detection guide I'm always getting no hits in the index lookup

### ISSUE THREAD

**Issue by eloygil** [GoogleCloudPlatform/cloud-vision#117]
The redis server is running. The credentials file for the API are set.
Now when I execute: 
./textindex.py ../../data/text/

I get:
../../data/text/sunbeamkitties.jpg already added to index.
../../data/text/mountain.jpg already added to index.
../../data/text/sabertooth.gif already added to index.
../../data/text/succulents.jpg already added to index.
../../data/text/bonito.gif already added to index.
../../data/text/wakeupcat.jpg already added to index.

Then I use python to try to find text:
>>> import textindex
>>> index = textindex.Index()
>>> index.print_lookup('cats')
No hits found.
>>> index.print_lookup('up')
No hits found.

Something is not working... I've tried with the 'up' string that is clearly in wakeupcat.jpg file, any idea?

Thank you.

**Comment by tswast** [comment]
Could you dump the whole redis database with a redis client? That will help with debugging.

**Comment by eloygil** [comment]
I am a newbie in redis, sorry for that. I'm using redis-cli and this is what I see, maybe it is not really useful, tell me any command I can run for you.

127.0.0.1:6379> config get databases
1) "databases"
2) "16"
127.0.0.1:6379> info keyspace
# Keyspace
db0:keys=43,expires=0,avg_ttl=0
db1:keys=8,expires=0,avg_ttl=0
127.0.0.1:6379> keys db0
(empty list or set)
127.0.0.1:6379> keys db1
(empty list or set)

**Comment by albertcere** [comment]
I have exactly the same problem.
Please, help!

**Comment by dizcology** [comment]
@eloygil Could you try and run the following in redis-cli:
`KEYS *`

Please note that the KEYS command expects a pattern as argument: [KEYS documentation](https://redis.io/commands/keys)

Then look at the listed keys to see if they are text appearing in your images.

Suppose "fish" shows up as one of the keys, then you should be able to run the following to find the image files that contain it:
`SMEMBERS fish`

[SMEMBERS documentation](https://redis.io/commands/smembers)

**Comment by eloygil** [comment]
@dizcology Thanks for your answer.
redis-cli command "KEYS *" is answering with 42 keys that match with the text in the images I indexed. Also, as you say, "up" isn't one of them. And... Yes, I misunderstood how KEYS worked, my bad.

If I use: "SMEMBERS human" I get:
1) "data/text/wakeupcat.jpg"
So it looks that it is working fine.

Then I go back to the proposed example and try to check from python:
>>> import textindex
>>> index = textindex.Index()
>>> index.print_lookup('human')
***Image data/text/wakeupcat.jpg has text:
Wake up human!
Wakeuphuman!
**>>> index.print_lookup('cats')**
No hits found.

Trying with 'human' now I have a hit but the proposed example was "cats" and it fails, is it a mistake there, or just an example of what doesn't get answers? Am I simply using a wrong example dataset? Anyway it looks like I can continue, but this may be confusing for others too.

Thank you.

**Comment by dizcology** [comment]
@eloygil Glad to know that you can continue with your project!

And indeed the word "cats" does not seem to appear on any of the images in (cloud-vision/data/text)[https://github.com/GoogleCloudPlatform/cloud-vision/tree/master/data/text].

**Comment by tswast** [comment]
Ah. Yeah, sounds like the readme should be updated to reflect the test data.

**Comment by abheek96** [comment]
**Unable to execute command ./textindex.py ../../data/text/**

The redis server is running. The credentials file for the API are set.

But when I try to execute-  ./textindex.py /Users/.../.../cloud-vision-master/data/text

I get- 
Traceback (most recent call last):
  File "./textindex.py", line 56, in <module>
    from googleapiclient import discovery
ImportError: No module named googleapiclient

**Comment by dizcology** [comment]
@abheek96 Please follow the setup steps on the [readme page](https://github.com/GoogleCloudPlatform/cloud-vision/blob/master/python/text/README.md).

Specifically the required packages are installed at this step:

```$ pip install -r requirements.txt```

**Comment by abheek96** [comment]
@dizcology followed each and every step as given in the readme page. Still cant understand as to why the error keeps occuring.

**Comment by dizcology** [comment]
@abheek96 did the pip install step succeed without errors?

Could you verify that googleapiclient (as well as the other packages listed in requirements.txt) was installed by running pip list?

**Comment by abheek96** [comment]
@dizcology following sequence of actions occured during the pip install step. 
<img width="1280" alt="issue" src="https://user-images.githubusercontent.com/24474820/27342558-29878ece-55fe-11e7-9abf-8608aaf2df7f.png">

**Comment by dizcology** [comment]
@abheek96 Thanks - could it be that there are multiple python versions on your system and not all of them could find the installed packages?  Run `which -a python` to find if there are.

If you run `python`, and then in the interactive session run `import googleapiclient`, do you get the same module not found error?

**Comment by abheek96** [comment]
@dizcology It shows the same error while running the import googleapiclient command. What can be done to solve the issue?
<img width="762" alt="issue1" src="https://user-images.githubusercontent.com/24474820/27374616-18416f7c-568a-11e7-9143-cd9549196014.png">

**Comment by dizcology** [comment]
@abheek96 [Here](https://stackoverflow.com/questions/32680081/importerror-after-successful-pip-installation) you can find some suggestions of how to deal with this ImportError.

If you run `pip list` do you see `google-api-python-client` listed?  

Looking at the previous screenshot you shared, it seems that the package collection step went through, but the step of actually installing packages failed while trying to uninstall `six`.  You might consider manually uninstall it with `pip uninstall six` before running `pip install -r requirements.txt` again.

**Comment by abheek96** [comment]
@dizcology  Thank you so much for your help! I was finally able to continue with my project. 
`I used sudo pip install -r requirements.txt --upgrade --ignore-installed six` command by which the google api client was properly installed. 

I would have been stuck without your help. Thank you!

**Comment by dizcology** [comment]
@abheek96 Happy to help.  Good luck with your project!
