### ISSUE TITLE
Android Example outdated. The used library will be deprecated soon

### ISSUE THREAD

**Issue by JohnFarl** [GoogleCloudPlatform/cloud-vision#135]
The documentation shows a message to not use `com.google.apis:google-api-services-vision:v1` for newer projects because the library actively maintained will be `com.google.cloud:google-cloud-vision` that cannot be used in the same way you have done in the sample since some method are missing and It uses a different procedure to access the cloud service.
Since this is the only official sample by Google. It should be updated as soon as possible.

**Comment by jerjou** [comment]
Hello -

Which sample are you looking at? Per the [README.md](https://github.com/GoogleCloudPlatform/cloud-vision/blob/master/README.md):

**This repo is being deprecated**. All new work can be found at a given
language's repo:

[C# / .NET][c#] | [Go lang][golang] | [Java][java] | [Node.js][nodejs] |
[PHP][php] | [Python][python] | [Ruby][ruby]

Note: The [Android](android/) and [IOS](ios/) samples haven't been moved to the
main [Android][android] and [IOS][ios] sample repos yet.

[c#]: //github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/vision/api
[golang]: //github.com/GoogleCloudPlatform/golang-samples/tree/master/vision
[java]: //github.com/GoogleCloudPlatform/java-docs-samples/tree/master/vision
[nodejs]: //github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/vision
[php]: //github.com/GoogleCloudPlatform/php-docs-samples/tree/master/vision
[python]: //github.com/GoogleCloudPlatform/python-docs-samples/tree/master/vision
[ruby]: //github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/vision
[android]: //github.com/GoogleCloudPlatform/android-docs-samples/
[ios]: //github.com/GoogleCloudPlatform/ios-docs-samples/

**Comment by seventhmoon** [comment]
Updated the project setup in #140.

For  choosing `com.google.apis:google-api-services-vision:v1` or `com.google.cloud:google-cloud-vision`. I think the current client library in Java is not very suitable for Android. Even AndroidThings(https://developer.android.com/things/training/doorbell/cloud-vision.html) example is still using the REST API wrapper.

I think we need to keep the REST API wrapper up-to-date or having an Android client library, instead of using the Java library for Android.

**Comment by aakashshah94** [comment]
I tried following the steps provided in the read me file for the android project setup and I am unable to run it. I understand this is because of some changes in the newer version of Android studio. Is there any updated android sample that provides a start-up code.
