### ISSUE TITLE
Document text detection in local PDF

### ISSUE THREAD

**Issue by mr-bjerre** [GoogleCloudPlatform/cloud-vision#146]
Having `path` point to a **local** image file I can segment and OCR the document using the following snippet

    from google.cloud import vision

    with open(path, 'rb') as image_file:
        content = image_file.read()
    image = vision.types.Image(content=content)

    client = vision.ImageAnnotatorClient()
    response = client.document_text_detection(image=image)

But I want to parse a **local** PDF or TIFF. It doesn't work with above (bad response) but I know Vision API can  parse the file types using `AsyncAnnotateFileRequest` which requires `InputConfig` and `OutputConfig`. To me it seems that this requires me to upload the pdf or tiff to either a google cloud bucket or some public accessible web address which I do not want (see [example](https://cloud.google.com/vision/docs/pdf)).

Is there some way to solve my problem?

**Comment by manojkarne** [comment]
Hello sir ,Now google accept pdf's but you have to store pdf on there cloud..

need help .
mail id
manojkarne22@gmail.com

**Comment by alvaroacev** [comment]
Hi,
Is Google considering to support sending the PDF as part of the request, just like it works with AnnotateImageRequest?

Thank you,
