### ISSUE TITLE
 I cant open the project on android

### ISSUE THREAD

**Issue by azoreG** [GoogleCloudPlatform/cloud-vision#147]
I have a problem opening the android project 

I get the following

Gradle 'CloudVision' project refresh failed
Error: Could not find method buildConfigField() for arguments [String, API_KEY, BuildType_Decorated .... 

why ?

**Comment by joshuayuan** [comment]
The readme is not accurate. You should go to your application's build.gradle file, and under `android { buildTypes { buildTypes.each { it.buildConfigField 'String', 'API_KEY', API_KEY }}}`, replace the third argument `API_KEY` with your API key string.
