### ISSUE TITLE
GoogleAPICallError: None Error in extracting images from PDF file

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/cloud-vision#155]
Hello,

I am using python version 2.7.5 and google-cloud-vision==0.35.2.
I'm getting the below error message, when converting pdf file to text. Few pdf files able to convert to text.

   _File "/usr/lib/python2.7/site-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
GoogleAPICallError: None Error in extracting images from PDF file gs://abc/xyz/test.pdf_

**Comment by 10001oleg** [comment]
the same error in NodeJS - vision API
