### ISSUE TITLE
Example iOS app 403s

### ISSUE THREAD

**Issue by iroller** [GoogleCloudPlatform/cloud-vision#16]
I followed the README and configured the Cloud Vision API key. Now I'm getting "Error code 403: Requests from this ios client application 'empty' are blocked". Any ideas?

**Comment by iroller** [comment]
It was related to bundle identifier. Got it fixed.

**Comment by iroller** [comment]
Actually does anyone know what's the proper way of sending bundle id to Vision API? It's always saying it's "empty".

**Comment by mateuszbuda** [comment]
@iroller I'm facing the same issue.
@sararob Can you tell if the problem is on the API side, iOS client side or maybe we should be more patient and wait longer for registering bundle identifier to take effect?

**Comment by tswast** [comment]
Looking at the Google Client Libraries for Objective C, it looks like the bundle ID is passed in as part of the user agent header for the request.
https://github.com/google/google-api-objectivec-client/blob/5b40ad6af9a806305a0a56d7cb91b82a27c26909/Source/Objects/GTLService.m

I think the sample is building the library manually instead of using that library. If so, we should update it to use the client library.

**Comment by tswast** [comment]
The sample is building the HTTP request manually, I mean.

**Comment by iroller** [comment]
I've tried using bundle id as User-Agent, it didn't help:
```
        if let bundleIdentifier = NSBundle.mainBundle().bundleIdentifier {
            NSUserDefaults.standardUserDefaults().registerDefaults(["UserAgent": bundleIdentifier])
        }
```

**Comment by mateuszbuda** [comment]
@iroller I can confirm that simply adding bundle id doesn't work. But it's strange that you add this to the `standardUserDefaults()` O.o
I've added bundle id as a `User-Agent` HTTP header:
```
if let bundleIdentifier = NSBundle.mainBundle().bundleIdentifier {
    request.addValue(bundleIdentifier, forHTTPHeaderField: "User-Agent")
}
```
I also tried to use `Google-API-Client` as a pod added to Swift project but run into this issue: https://github.com/google/google-api-objectivec-client/issues/83

And now I'm working out how to use it in Obj-C. Maybe you know any examples or have any hints how to translate existing code into `Google-API-Client`?

**Comment by tswast** [comment]
@sararob Could you look at switching to the Google API Client Libraries for the iOS samples? Now that the Vision API is in public beta, we should be able to post the generated code for them, if they aren't already up somewhere.

**Comment by iroller** [comment]
@mateuszbuda oops, that was a wrong copy-pasta. I'm setting User-Agent in `standardUserDefaults() ` for UIWebViews, not relevant here. Thanks for noticing.

**Comment by amurray4** [comment]
I am also facing this issue

**Comment by rusurazvangabriel** [comment]
Try using the Web API Key instead of the iOS API key. I had the same issue but now it works.

**Comment by mateuszbuda** [comment]
@rusurazvangabriel It worked, thanks!

**Comment by tswast** [comment]
I've got https://github.com/GoogleCloudPlatform/cloud-vision/pull/34 pending which should fix the samples to allow using the iOS API Key. The important bit is to populate the `X-Ios-Bundle-Identifier` header.

Swift:

```swift
request.addValue(NSBundle.mainBundle().bundleIdentifier ?? "", forHTTPHeaderField: "X-Ios-Bundle-Identifier")
```

Objective-C:

```objc
[request addValue:[[NSBundle mainBundle] bundleIdentifier] forHTTPHeaderField:@"X-Ios-Bundle-Identifier"];
```

**Comment by iroller** [comment]
This did a trick for me in Swift. Thanks @tswast !

**Comment by TamilRaja** [comment]
I also same like this error in my google calendar ios app. Kindly update the answer.
Error : disallowed_useragent
my pod file
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'PodDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  use_frameworks!

  # Pods for PodDemo
pod 'GoogleAPIClient/Calendar', '~> 1.0.2'
pod 'GTMOAuth2', '~> 1.1.0'
pod 'GTMAppAuth'

end

**Comment by lane-faison** [comment]
I have recently run into the same Error 403 when trying to run this sample project on my iPhone. I solved the problem by going into my Credentials on the Google API site, clicking on "API Key" and adding in the bundle identifier. Normally the bundle identifier should already be there, but since I was using an API key from another project, it wasn't listed, thus creating the 403. I hope this helps someone!
