### ISSUE TITLE
Cloud Vision API request failed. Check logs for details.

### ISSUE THREAD

**Issue by FerialMuhammad** [GoogleCloudPlatform/cloud-vision#162]
I followed all the steps and got the API key and put it in the gradle file. The app runs without issues but when I choose a photo from gallery it uploads and shows this message "Cloud Vision API request failed. Check logs for details." what am I doing wrong?

**Comment by PAdhikary115** [comment]
Getting javax.net.ssl.SSLHandshakeException: Handshake failed error. What is the issue?
