### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by georgezoto** [GoogleCloudPlatform/cloud-vision#168]
Hi there,

Great app and collection of services! When I start the crawler and visit the main external IP of the awwvision-webapp I see classification labels and the source code, the image urls on reddit. However none of the images are showing on any of my browsers (Chrome v78 or Safari v13).

Can someone point me in the right direction on how to have the images showing?

Thank you,
George

<img width="1181" alt="Screen Shot 2019-11-13 at 8 29 19 AM" src="https://user-images.githubusercontent.com/16548373/68768006-b5953a80-05ef-11ea-81d2-c9cfcea5cdf7.png">

**Comment by Vipul-1998** [comment]
I would like to contribute in this.
