### ISSUE TITLE
Awwwvision web server not rendering images

### ISSUE THREAD

**Issue by seanlubbers1** [GoogleCloudPlatform/cloud-vision#171]
There is an issue with the awwwvision source code—the images are not being properly rendered when the web app is used.

Everything works smoothly up until the point where we kick off deployment. After I hit the start crawler button and then go back no images are displayed:

<img width="1674" alt="Screen Shot 2019-12-03 at 3 14 25 PM" src="https://user-images.githubusercontent.com/39922333/70193777-11198c00-16b5-11ea-88b1-6eff00c1e178.png">

I did a little bit more inspection with dev tools, and it looks like the image URLs are misformatted:

<img width="554" alt="Screen Shot 2019-12-03 at 11 28 20 AM" src="https://user-images.githubusercontent.com/39922333/70193854-59d14500-16b5-11ea-8071-55ad6a4349f4.png">

It looks like the image preview URLs are not being properly decoded, as we can see here they have a 'b' prefixed:

<img width="550" alt="Screen Shot 2019-12-03 at 11 28 48 AM" src="https://user-images.githubusercontent.com/39922333/70193900-7ff6e500-16b5-11ea-81b4-31234386fbf7.png">

Tried decoding myself in multiple functions throughout the source code, but haven't had any luck. 

Requesting an update to this one. One of our highly used qwiklabs  "Awwvision: Cloud Vision API from a Kubernetes Cluster" relies on this repo and cannot be used until changes are made.

**Comment by gogasca** [comment]
I will take a look at this one.

**Comment by gogasca** [comment]
Container uses Python 3.6.8

```
Python 3.6.8 (default, Feb  2 2019, 01:34:17) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by gogasca** [comment]
Fixed in: https://github.com/GoogleCloudPlatform/cloud-vision/pull/172 looking for a reviewer

**Comment by gogasca** [comment]
#172 has been merged
