### ISSUE TITLE
error: unable to recognize "spec.yaml": no matches for kind "Deployment" in version "apps/v1beta1"

### ISSUE THREAD

**Issue by adilshehzad786** [GoogleCloudPlatform/cloud-vision#180]
make all command -

make -C redis all
make[1]: Entering directory '/home/student_04_6a8cfa2ca541/cloud-vision/python/awwvision/redis'
kubectl create -f spec.yaml
service/redis-master created
error: unable to recognize "spec.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
make[1]: *** [Makefile:6: deploy] Error 1
make[1]: Leaving directory '/home/student_04_6a8cfa2ca541/cloud-vision/python/awwvision/redis'
make: *** [Makefile:9: redis] Error 2

**Comment by nitinvinayak** [comment]
Use this repo https://github.com/nitinvinayak/cloud-vision for git clone statement, it will solve the issue you are facing and you will be able to complete the lab. I was having the same trouble, I found the fix in one of the open issue pull request.

git clone https://github.com/nitinvinayak/cloud-vision

**Comment by doaamostafa67988** [comment]
i used it but it didnt work

**Comment by Az1m04** [comment]
> i used it but it didnt work
Hey Watch this ;

https://youtu.be/ziaBp3vxii0

make all cammand problem solution

**Comment by ninjaasmoke** [comment]
> > i used it but it didnt work
> > Hey Watch this ;
> 
> https://youtu.be/ziaBp3vxii0
> 
> make all cammand problem solution

Still getting same error for some reason

**Comment by Az1m04** [comment]
> > > i used it but it didnt work
> > > Hey Watch this ;
> > 
> > 
> > https://youtu.be/ziaBp3vxii0
> > make all cammand problem solution
> 
> Still getting same error for some reason
 


Lab name ?

**Comment by nitinvinayak** [comment]
This is the lab.
Awwvision: Cloud Vision API from a Kubernetes Cluster(https://google.qwiklabs.com/focuses/1241?parent=catalog)

The repository(https://github.com/nitinvinayak/cloud-vision) worked for me 3 days back.

**Comment by Az1m04** [comment]
still facing issue ?

**Comment by Az1m04** [comment]
> > > i used it but it didnt work
> > > Hey Watch this ;
> > 
> > 
> > https://youtu.be/ziaBp3vxii0
> > make all cammand problem solution
> 
> Still getting same error for some reason


Contact me on linkedin: https://www.linkedin.com/in/mdazimbabu/ and  Share the screenshot where you got error

**Comment by ninjaasmoke** [comment]
> > > > i used it but it didnt work
> > > > Hey Watch this ;
> > > 
> > > 
> > > https://youtu.be/ziaBp3vxii0
> > > make all cammand problem solution
> > 
> > 
> > Still getting same error for some reason
> 
> Contact me on linkedin: https://www.linkedin.com/in/mdazimbabu/ and Share the screenshot where you got error

I completed the lab! Thank you!

**Comment by Az1m04** [comment]
> > > > > i used it but it didnt work
> > > > > Hey Watch this ;
> > > > 
> > > > 
> > > > https://youtu.be/ziaBp3vxii0
> > > > make all cammand problem solution
> > > 
> > > 
> > > Still getting same error for some reason
> > 
> > 
> > Contact me on linkedin: https://www.linkedin.com/in/mdazimbabu/ and Share the screenshot where you got error
> 
> I completed the lab! Thank you!



apps/v1 not v1beta1

Congrats 🎉

**Comment by adilshehzad786** [comment]
Finally, Issue Solved! Thank You, Everyone

**Comment by Az1m04** [comment]
Good to hear that👍
