### ISSUE TITLE
error in qwiklab on command ''make all'' lab is Awwvision

### ISSUE THREAD

**Issue by umair313** [GoogleCloudPlatform/cloud-vision#181]
(venv) student_00_c0a723f48ece@cloudshell:~ (qwiklabs-gcp-00-215a313ffde9)$ git clone https://github.com/GoogleCloudPlatform/cloud-vision
Cloning into 'cloud-vision'...
remote: Enumerating objects: 1517, done.
remote: Total 1517 (delta 0), reused 0 (delta 0), pack-reused 1517
Receiving objects: 100% (1517/1517), 3.97 MiB | 2.31 MiB/s, done.
Resolving deltas: 100% (558/558), done.
(venv) student_00_c0a723f48ece@cloudshell:~ (qwiklabs-gcp-00-215a313ffde9)$ cd cloud-vision/python/awwvision
(venv) student_00_c0a723f48ece@cloudshell:~/cloud-vision/python/awwvision (qwiklabs-gcp-00-215a313ffde9)$ make all
make -C redis all
make[1]: Entering directory '/home/student_00_c0a723f48ece/cloud-vision/python/awwvision/redis'
kubectl create -f spec.yaml
service/redis-master created
error: unable to recognize "spec.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
make[1]: *** [Makefile:6: deploy] Error 1
make[1]: Leaving directory '/home/student_00_c0a723f48ece/cloud-vision/python/awwvision/redis'
make: *** [Makefile:9: redis] Error 2
(venv) student_00_c0a723f48ece@cloudshell:~/cloud-vision/python/awwvision (qwiklabs-gcp-00-215a313ffde9)$ exit

**Comment by nitinvinayak** [comment]
Use this repo https://github.com/nitinvinayak/cloud-vision for git clone statement, it will solve the issue you are facing and you will be able to complete the lab. I was having the same trouble, I found the fix in one of the open issue pull request.

git clone https://github.com/nitinvinayak/cloud-vision

**Comment by umair313** [comment]
Thank you
