### ISSUE TITLE
AttributeError: 'ImageAnnotatorClient' object has no attribute 'text_detection'

### ISSUE THREAD

**Issue by RubensZimbres** [GoogleCloudPlatform/cloud-vision#186]
I'm using the code from Google Cloud site but I'm getting an error `AttributeError: 'ImageAnnotatorClient' object has no attribute 'text_detection'`

The code used:

`import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/home/rubens1234.json"

from google.cloud import storage
from google.cloud import vision #anaconda ?
from google.cloud.vision import types
import base64
import json
import os
import re

def detect_text(path):
    """Detects text in the file."""
    texto=[]
    from google.cloud import vision
    import io
    client = vision.ImageAnnotatorClient()

    with io.open(path, 'rb') as image_file:
        content = image_file.read()

    image = vision.types.Image(content=content)

    response = client.text_detection(image=image)
    texts = response.text_annotations
    print('Texts:')

    for text in texts:
        print('\n"{}"'.format(text.description))
        texto.append(text.description)
        vertices = (['({},{})'.format(vertex.x, vertex.y)
                    for vertex in text.bounding_poly.vertices])

        print('bounds: {}'.format(','.join(vertices)))

    if response.error.message:
        raise Exception(
            '{}\nFor more info on error messages, check: '
            'https://cloud.google.com/apis/design/errors'.format(
                response.error.message))
    return re.sub("\n","",' '.join(texto))
`

I already tried 5 different versions of the library google-cloud-vision and none of them is working. However, when code is copied to a new python notebook, *eventually* runs.

Any ideas on how to solve this issue ?

**Comment by meredithslota** [comment]
To file a bug with the library itself, please see: https://github.com/googleapis/python-vision/issues — I did search there and found similar issues that have since been closed, so perhaps this issue is already resolved.
