### ISSUE TITLE
Cannot import vision from google.cloud

### ISSUE THREAD

**Issue by RubensZimbres** [GoogleCloudPlatform/cloud-vision#187]
Hi. I've been having problems with Cloud Vision, mainly due to its dependencies. In my Compute Engine instance I use google.cloud.vision with the following set up:

google-api-core                   1.22.1
google-api-python-client          1.11.0
google-auth                       1.21.0
google-auth-httplib2              0.0.4
google-auth-oauthlib              0.4.0
google-cloud                      0.34.0
google-cloud-bigquery             1.20.0
google-cloud-core                 0.26.0
google-cloud-dataproc             0.5.0
google-cloud-datastore            1.9.0
google-cloud-language             1.3.0
google-cloud-logging              1.13.0
google-cloud-monitoring           0.31.1
google-cloud-spanner              1.10.0
google-cloud-speech               1.3.2
google-cloud-storage              1.20.0
google-cloud-translate            1.6.0
google-compute-engine             20190916.0
google-gax                        0.15.16
google-images-download            2.8.0
google-pasta                      0.1.8
google-resumable-media            0.4.1
googleapis-common-protos          1.52.0
grpc-google-iam-v1                0.12.3

This works perfectly. However, I am being unable to reproduce a Python code in another VM instance (Debian with anaconda) because *cannot import vision from google.cloud*. Not because of google-cloud library itself, 0.34.0, but because of its dependencies, what makes very very difficult to find out which cloud vision dependency is not updated/right version.

This is even worse when I am dealing with a Python notebook that handles Natural Language Processing, Computer Vision and OCR. I am dependent of a snapshot I did, but if I try to reproduce the pip list above is quite impossible, given that they have to be installed in a specific order, or else the latest library installed will overwrite previous versions of the other google cloud libraries. Also a problem for Dockerfiles in Kubernetes.

**Comment by meredithslota** [comment]
To file a bug with the library itself, please see: https://github.com/googleapis/python-vision/issues — I did search there and found similar issues that have since been closed, so perhaps this issue is already resolved.
