### ISSUE TITLE
CloudVision, returns an error "Requests from this Android client application <empty> are blocked"

### ISSUE THREAD

**Issue by sekhar15aug** [GoogleCloudPlatform/cloud-vision#27]
sample.google.com.cloudvision D/MainActivity﹕ failed to make API request because {
    "code": 403,
    "errors": [
    {
    "domain": "global",
    "message": "Requests from this Android client application <empty> are blocked.",
    "reason": "forbidden"
    }
    ],
    "message": "Requests from this Android client application <empty> are blocked.",
    "status": "PERMISSION_DENIED"
    }

**Comment by sekhar15aug** [comment]
http://stackoverflow.com/questions/35531854/google-cloud-vision-api-permission-denied

**Comment by tswast** [comment]
@sekhar15aug Any chance you have set the bundle identifier in the API key? I'm guessing this might be the same issue we are seeing for the iOS samples. github.com/GoogleCloudPlatform/cloud-vision/issues/16 I will see if maybe there's an Android-specific set of client libraries we should be using instead of the Java ones.

**Comment by sekhar15aug** [comment]
@tswast I have changed only CLOUD_VISION_API_KEY with my API key.

**Comment by seanlinamt** [comment]
I had the same problem before. 
But I solved this by using Browser API Key.

**Comment by smholsen** [comment]
I am having this same issue still. 
It seems the package name is not sent with the request, 
I also got this: W/AbstractGoogleClient: Application name is not set. Call Builder#setApplicationName.
Could this have something to do with it?

**Comment by phandinhloc** [comment]
We have the same problem when using on Android app (google-api-services-vision:v1-rev24-1.22.0). It works only if no restrict.

**Comment by smholsen** [comment]
Nice to hear I am not the only one :)
I am going to look at this during my christmas holiday, (have to focus on finals for now).
I will keep you updated if I find out anything. 
Using no restrict is a serious security issue, and I would advice not to publish any android application without restritcted access on the API key. I have not done any research on this yet, so I do not know for certain wether or how the information i encrypted and if it can be intercepted. But without restriction on the API key your key could potentially be sniffed and abused. 
(If you worry your key can have gotten gone astray then you can delete or or regen a new)
I will update here whenever (if) I figure anything out, and I hope you can do the same! :)

**Comment by smholsen** [comment]
Thank you @jerjou ! 👍 
Cant wait to try it out :)

**Comment by tswast** [comment]
I was able to use Jerjou's changes with a restricted key. Let us know if you still have trouble with it.

**Comment by jerjou** [comment]
Sorry for the long delay, all. We were trying to figure out the Best Way to do this (the way I merged is a little more esoteric than it can be), but clearly weren't making very fast progress :-/ Anyway, this way should be fine, and is certainly better than before, so we can at least unblock you all.
