### ISSUE TITLE
Chrome label detection not functional

### ISSUE THREAD

**Issue by bobobo1618** [GoogleCloudPlatform/cloud-vision#57]
I installed a build of the Chrome extension from the webstore and although "Face detection" displays an image and "Text detection" copies to my clipboard, "label detection" doesn't appear to have any effect.

**Comment by tswast** [comment]
Could you share an example image that you are using it with?

**Comment by bobobo1618** [comment]
Here's one, just came up when I searched Google Images for "bear": ![](http://geology.com/stories/13/bear-areas/grizzly-bear.jpg)

**Comment by ImJasonH** [comment]
I'm not able to reproduce this. Are you using v0.0.9 of the extension? There was a bug with v0.0.8 which was fixed yesterday, maybe that was the problem?

![screenshot from 2016-03-25 11 50 19](https://cloud.githubusercontent.com/assets/210737/14047729/f719250c-f27f-11e5-9dda-c18ed7f6096b.png)

**Comment by bobobo1618** [comment]
Yeah, seems I was using v0.0.8. v0.0.9 works fine, thanks!
