### ISSUE TITLE
Errors : error Bad Request

### ISSUE THREAD

**Issue by Wafrettes** [GoogleCloudPlatform/cloud-vision#71]
![screenshot 26](https://cloud.githubusercontent.com/assets/18457461/14662968/0d8f13aa-06ee-11e6-972e-cfca1cf5634a.png)

How do I fix this?

**Comment by tswast** [comment]
Which sample are you running? Is this happening for all images or a specific image? If only a specific image, could you link to a copy of it?

**Comment by Wafrettes** [comment]
It happens to all picture that I choose. Including those pictures that have been used in the tutorials.

**Comment by Wafrettes** [comment]
And what do you mean sample?

**Comment by tswast** [comment]
Are you running one of the sample applications / tutorials? If so, which one?

**Comment by Wafrettes** [comment]
https://github.com/GoogleCloudPlatform/cloud-vision/tree/master/js . That. We followed the instructions as instructed in README.md

**Comment by tswast** [comment]
When you wrote `key.js` did you include the `[` and `]` characters? When I do that, I get the same message "ERRORS: error". When I look in the console in my browser I see "Failed to load resource: the server responded with a status of 400 ()".

When I remove the `[` and `]` characters, I see a valid response.

Is this the issue you are having?

I will fix the README. It is confusing right now.

**Comment by Wafrettes** [comment]
No i did not. Only the apostrophes.

**Comment by tswast** [comment]
Do you see any output in the browser console? Please be careful sharing that, as it can contain your private key.

**Comment by Wafrettes** [comment]
I'll check.

**Comment by Wafrettes** [comment]
![screenshot 28](https://cloud.githubusercontent.com/assets/18457461/14729596/df1500c2-0871-11e6-993e-9e0904326c1b.png)

**Comment by tswast** [comment]
Interesting. Odd that there aren't any bad network requests showing up. If it is a valid browser key, the only other thing I can think of is that the Vision API is not enabled. This link should enable it for the project you select if it is not yet enabled: https://console.cloud.google.com/flows/enableapi?apiid=vision.googleapis.com

**Comment by Wafrettes** [comment]
![screenshot 29](https://cloud.githubusercontent.com/assets/18457461/14729794/7b519508-0873-11e6-822a-aa4b15acf069.png)

**Comment by tswast** [comment]
Hooray!

**Comment by Wafrettes** [comment]
It worked already, but, won't it return an image? if not, is there a way?

**Comment by tswast** [comment]
No, the Vision API does not return an image. It only processes the image. For hosting images, you will likely want a server-side component that stores the image in Google Cloud Storage after uploading.

I don't think we have a combination sample, but we do have samples for Cloud Storage in many languages. Here is the one for Node.js https://cloud.google.com/nodejs/getting-started/using-cloud-storage

**Comment by Wafrettes** [comment]
Ohhh. Too bad, I hope it's like java, cause it returns a picture with the faces enclosed with green box.
