### ISSUE TITLE
Javascript output

### ISSUE THREAD

**Issue by Wafrettes** [GoogleCloudPlatform/cloud-vision#73]
Hi, this is an ouput from Java using eclipse
![1f1e040e8b2b55bca602e6fba21bd6bf9df84ee466d9e9308a pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/18457461/14804925/0487654a-0b9a-11e6-9c48-8bacf9404bb7.jpg)

and this is an output from javascript
![screenshot 29](https://cloud.githubusercontent.com/assets/18457461/14804946/3548f108-0b9a-11e6-8201-f5fdd4bfeb5b.png)

Our goal is to identify the sentiment of the faces being detected. In java, it can only detect faces, but no sentiment analysis. In Javascript, it can detect and identify the sentiment. Our problem is, it does not return pictures for us to easily know how many faces are detected. Is there a way for this?

**Comment by jerjou** [comment]
Hello-

The samples are meant more as a starting point that you can add to and modify for your needs.

For example, the java sample doesn't actually get the image back from the API - it just gets the same metadata that the javascript sample does. It's just that, after it receives the metadata, it uses a java drawing library to take the image (that it still has) and draw boxes at the coordinates specified by the metadata it got from the api. It could also have used the sentiment metadata that the api returns to do something with the sentiment as well.

The javascript sample, in turn, just displays the metadata in its raw json format. You could extend it to, for example, use a canvas to draw the original image, and then draw boxes around all the faces, and do something with the sentiment as well.

That is to say - either sample can be modified to do what the other sample does, and more. They're just there to demonstrate how to use the api, but you can modify the code to use the metadata however you like.

**Comment by Wafrettes** [comment]
Thank you :)
