### ISSUE TITLE
PHP example not working on AppEngine

### ISSUE THREAD

**Issue by adammeyer** [GoogleCloudPlatform/cloud-vision#74]
The example works great locally, but fails in AppEngine.  I get a curl error #7, cannot connect to host.  From some reading online, it looks like https://vision.googleapis.com calls are blocked by AppEngine.

Can anyone confirm this?  Any work arounds?

**Comment by tswast** [comment]
@tmatsuo Could you take a look? Is the Cloud Vision PHP sample https://github.com/GoogleCloudPlatform/cloud-vision/tree/master/php/LandmarkDetection hitting the API endpoint in the right way?

**Comment by adammeyer** [comment]
Thanks @tswast- I switched my code to use file_get_contents instead of CURL, and it worked great.  I got the example from this page: https://cloud.google.com/appengine/docs/php/outbound-requests

**Comment by tmatsuo** [comment]
On app engine, you have to have `php.ini` with the following content:

```
google_app_engine.enable_curl_lite
```

to enable curl.

**Comment by tmatsuo** [comment]
@adammeyer `file_get_contents` is working, so the vision API endpoint is clearly not blocked :)
Please try enabling curl by having the `php.ini` and let me know how it goes.

**Comment by tmatsuo** [comment]
I think we can close this issue. Feel free to re-open @adammeyer
