### ISSUE TITLE
BoundingPoly for LABEL_DETECTION

### ISSUE THREAD

**Issue by jshin49** [GoogleCloudPlatform/cloud-vision#75]
This may not be relevant to be an issue in this repository, but it might be in everyone's best interest.

I have been wondering when or if there are any plans of implementing boundingPoly's for the label detection feature.

I know it is hard but it just seems so great to imagine such a feature.

Many thanks.

p.s. if there are any workarounds for this matter, that would be great to know.

**Comment by jerjou** [comment]
Thanks for the feedback! I'll pass it along to the relevant parties.

**Comment by tsulz** [comment]
Just curious, have there been any updates on boundingPoly's for LABEL_DETECTION?
