### ISSUE TITLE
Multilaguage support android

### ISSUE THREAD

**Issue by ShraddhaGadesha** [GoogleCloudPlatform/cloud-vision#80]
Which languages are supported by vision api for ocr.

**Comment by jerjou** [comment]
You can check out the [api reference](https://cloud.google.com/vision/reference/rest/v1/images/annotate) for the authoritative answer. In this case, if you take a look at the [imageContext](https://cloud.google.com/vision/reference/rest/v1/images/annotate#annotateimagerequest) object you can send with the `annotate` request, there's a `languageHints` property you can set. The description of the property references the translate api, which has a list of supported languages [here](https://cloud.google.com/translate/v2/translate-reference#supported_languages).
