### ISSUE TITLE
Unicode fractions not detected for TEXT_DETECTION

### ISSUE THREAD

**Issue by jamesmfriedman** [GoogleCloudPlatform/cloud-vision#81]
When using the cloud vision api for OCR, it doesn't like unicode fractions. I'm using it for a recipe project I'm working on, so fractions are kind of a big deal ;).

![image](https://cloud.githubusercontent.com/assets/975256/16098659/3e02fb90-3322-11e6-8f79-442f5d0468c3.png)

Loving the Vision API!

**Comment by tswast** [comment]
Thanks for your feedback, I'll pass it on to the team.
