### ISSUE TITLE
Sample App for Node.js client

### ISSUE THREAD

**Issue by jshin49** [GoogleCloudPlatform/cloud-vision#82]
Hi, This isn't an issue, but I didn't know where to post.

I have a sample Facebook Messenger Bot using the Google Cloud Vision API.

I'm leaving the link for it here for people who might want to refer to it.

[fb-vision-bot](https://github.com/jshin49/fb-vision-bot)

Thank you.

**Comment by tswast** [comment]
Thanks for sharing!

I wonder if we (Google Cloud) should make an [awesome](https://github.com/sindresorhus/awesome) for samples like this?

**Comment by tswast** [comment]
I added this to the https://github.com/GoogleCloudPlatform/awesome-google-cloud#google-cloud-vision repository!

Your project is one of the first awesome projects listed. Thanks again for sharing.
