### ISSUE TITLE
I want to print out all the text present in an image.

### ISSUE THREAD

**Issue by Milap7** [GoogleCloudPlatform/cloud-vision#94]
I am trying to use Vision APi for ANPR. Instead of passing queries, i just want to know the text in an image(license plate in the picture of the car). How do i do that?

**Comment by Milap7** [comment]
Also how do i use extrac_description(text): what is the input argument?

**Comment by jerjou** [comment]
Which sample are you referring to? Can you provide the file path for the sample you're using?

**Comment by mehmetdniz** [comment]
@Milap7 hi,

Did you use it with the ANPR library?

I want to do the same thing. Could you help.

**Comment by tswast** [comment]
Please see the documentation for the OCR features: https://cloud.google.com/vision/docs/detecting-text

Note that the Google Vision API is a general-purpose model, though it may work well for Automatic Number Plate Recognition.
