### ISSUE TITLE
Broken Links in README.md  [404]

### ISSUE THREAD

**Issue by vinayakagrawal88** [GoogleCloudPlatform/cloud-vision#96]
Broken Links 
Landmark Detection Using Google Cloud Storage:
-Documentation and Java Code

Face Detection
-Python Code
-Java Code

Label Detection
-Python Code
-Java Code

Text Detection Using the Vision API
-Documentation and Java Code

**Comment by jerjou** [comment]
Thanks for reporting! Fixed in #97
