### ISSUE TITLE
Vision-Label Detection returns blank response for a specific image

### ISSUE THREAD

**Issue by dapper-hacker** [GoogleCloudPlatform/cloud-vision#98]
Hi, 
When using the Label Detection in Vision API, during my testing one specific image doesnt get labelled at all. Infact it breaks the label.py code since the response is empty. 

Steps to reproduce : 
Use label.py to score image attached with this issue. 
![nailclipper](https://cloud.githubusercontent.com/assets/7928115/19330887/0146955a-9096-11e6-9eee-d06a1d1ca17e.jpg)

My Testing (I Changed label.py code to print complete 'response' object): 

```
c:\BigData\google\api\python-docs-samples\vision\api\label>python label.py ./res
ources/nailpaint.jpg
{'responses': [{'labelAnnotations': [{'score': 0.96202141, 'mid': '/m/0p833', 'd
escription': 'perfume'}]}]}

c:\BigData\google\api\python-docs-samples\vision\api\label>python label.py ./res
ources/nailclipper.jpg
{'responses': [{}]}
```

**Comment by staturecrane** [comment]
I am having this exact same issue. @vinayakagrawal88 Did you ever find a solution to this?

**Comment by swayam18** [comment]
Any updates on this issue? It's frustrating to get empty responses.
